import { Product } from "./types";

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    nazwa: "MacBook Pro 14\"",
    sku: "MBP14M3PRO",
    opis: "Wydajny laptop do zastosowań profesjonalnych z procesorem M3 Pro.",
    producent: "Apple",
    kategoria: "Komputery",
    cechy: ["WiFI", "USB-C", "Premium"],
    cenaNetto: 8129.27,
    cenaBrutto: 9999.0,
    vat: 23,
    waluta: "PLN",
    czyDostepny: true,
    czyLimitowany: false,
    iloscMagazyn: null,
    minKoszyk: 1,
    maxKoszyk: 5,
    createdAt: "2026-09-17T10:00:00.000Z",
  },
  {
    id: "prod-2",
    nazwa: "Galaxy S24 Ultra",
    sku: "SGS24U256",
    opis: "Flagowy smartfon z tytanową ramką i zaawansowanym aparatem.",
    producent: "Samsung",
    kategoria: "Telefony",
    cechy: ["WiFI", "Bluetooth", "USB-C", "Wodoodporny", "Premium"],
    cenaNetto: 5121.14,
    cenaBrutto: 6299.0,
    vat: 23,
    waluta: "PLN",
    czyDostepny: true,
    czyLimitowany: true,
    iloscMagazyn: 45,
    minKoszyk: 1,
    maxKoszyk: 3,
    createdAt: "2026-09-17T10:05:00.000Z",
  },
  {
    id: "prod-3",
    nazwa: "Sony WH-1000XM5",
    sku: "SNWH1000XM5",
    opis: "Słuchawki bezprzewodowe z wiodącą w branży redukcją hałasu.",
    producent: "Sony",
    kategoria: "RTV",
    cechy: ["Bluetooth", "Bezprzewodowy", "Premium"],
    cenaNetto: 1300.0,
    cenaBrutto: 1599.0,
    vat: 23,
    waluta: "PLN",
    czyDostepny: true,
    czyLimitowany: false,
    iloscMagazyn: null,
    minKoszyk: 1,
    maxKoszyk: 5,
    createdAt: "2026-09-17T10:10:00.000Z",
  },
  {
    id: "prod-4",
    nazwa: "Bosch Serie 6 WAU28P40",
    sku: "BSWAU28P40",
    opis: "Energooszczędna pralka z technologią EcoSilence Drive.",
    producent: "Bosch",
    kategoria: "AGD",
    cechy: ["Ekologiczny"],
    cenaNetto: 2682.11,
    cenaBrutto: 3299.0,
    vat: 23,
    waluta: "PLN",
    czyDostepny: false,
    czyLimitowany: true,
    iloscMagazyn: 0,
    minKoszyk: 1,
    maxKoszyk: 1,
    createdAt: "2026-09-17T10:15:00.000Z",
  },
  {
    id: "prod-5",
    nazwa: "Xiaomi Smart Band 8",
    sku: "XMSB8BLK",
    opis: "Inteligentna opaska sportowa z ekranem AMOLED 60Hz.",
    producent: "Xiaomi",
    kategoria: "Akcesoria",
    cechy: ["Bluetooth", "Wodoodporny", "Bezprzewodowy"],
    cenaNetto: 145.53,
    cenaBrutto: 179.0,
    vat: 23,
    waluta: "PLN",
    czyDostepny: true,
    czyLimitowany: false,
    iloscMagazyn: null,
    minKoszyk: 1,
    maxKoszyk: 10,
    createdAt: "2026-09-17T10:20:00.000Z",
  },
  {
    id: "prod-6",
    nazwa: "Dell UltraSharp U2723QE",
    sku: "DLU2723QE",
    opis: "Monitor 27\" 4K IPS Black z łącznością USB-C hub.",
    producent: "Apple",
    kategoria: "Komputery",
    cechy: ["USB-C", "Premium"],
    cenaNetto: 2356.91,
    cenaBrutto: 2899.0,
    vat: 23,
    waluta: "PLN",
    czyDostepny: true,
    czyLimitowany: true,
    iloscMagazyn: 12,
    minKoszyk: 1,
    maxKoszyk: 4,
    createdAt: "2026-09-17T10:25:00.000Z",
  },
  {
    id: "prod-7",
    nazwa: "Apple iPad Air M2",
    sku: "APIPADAIRM2",
    opis: "Lekki i wydajny tablet ze zjawiskowym ekranem Liquid Retina.",
    producent: "Apple",
    kategoria: "Komputery",
    cechy: ["WiFI", "Bluetooth", "USB-C", "Premium"],
    cenaNetto: 2844.72,
    cenaBrutto: 3499.0,
    vat: 23,
    waluta: "PLN",
    czyDostepny: true,
    czyLimitowany: true,
    iloscMagazyn: 8,
    minKoszyk: 1,
    maxKoszyk: 2,
    createdAt: "2026-09-17T10:30:00.000Z",
  },
];
